import AdSlot from '../components/AdSlot';
import useHead from '../hooks/useHead';
import { SITE_NAME, SITE_URL, absoluteUrl, SITE_DEFAULT_IMAGE } from '../site-config';

const ABOUT_AD_SLOT = import.meta.env.VITE_ADSENSE_SLOT_ABOUT;

export default function AboutPage() {
  useHead({
    title: `About \u2014 ${SITE_NAME}`,
    description: 'Meet Henry, an 8-year-old comic artist, and learn how every comic on the shop is made — from sticky-note idea to scanned page.',
    canonical: SITE_URL + '/about',
    ogImage: absoluteUrl(SITE_DEFAULT_IMAGE),
  });

  return (
    <article className="legal-page">
      <header className="legal-page-header">
        <h2 className="section-title">About Henry &amp; the Comic Shop</h2>
        <p className="legal-meta">A free vault of original comics by an 8-year-old.</p>
      </header>

      <section className="legal-section">
        <div className="about-page-hero">
          <div className="henry-avatar henry-avatar-lg">
            <img src="/henry-avatar.png" alt="Henry" />
          </div>
          <div>
            <h3>Meet Henry</h3>
            <p>
              Henry is 8 years old and has been drawing his own comics since
              kindergarten. The very first ones were stick-figure superheroes on
              the back of takeout menus. Now he fills entire stacks of sketchbooks
              with dragons, dudes in pursuit, lightsaber duels, lava monsters, and
              the occasional skeleton king.
            </p>
            <p>
              Henry&apos;s Comic Shop is his way of getting those comics in front of
              other kids (and curious grown-ups). Every story, every character,
              and every dramatically-misspelled sound effect on this site is his
              own. Nothing here was generated by a computer.
            </p>
          </div>
        </div>
      </section>

      <section className="legal-section">
        <h3>How a comic gets made</h3>
        <p>
          Most comics start as a single idea Henry sketches on a sticky note:
          &ldquo;dragon egg&rdquo;, &ldquo;ink monster&rdquo;, &ldquo;the bones
          are coming&rdquo;. From there he plans the panels in pencil, inks them
          with markers, adds color when he&apos;s in the mood, and then a parent
          scans the pages so they can go up on the site.
        </p>
        <p>
          Some comics are short and punchy (one or two pages). Others are full
          multi-issue series &mdash; the Dragon Series wrapped up at four issues,
          and Who Knows? has a bonus middle book that you read <em>after</em>{' '}
          the finale. Sequels happen whenever Henry feels like a story isn&apos;t done
          yet.
        </p>
      </section>

      <AdSlot slot={ABOUT_AD_SLOT} className="ad-slot-inline" />

      <section className="legal-section">
        <h3>The series so far</h3>
        <ul>
          <li>
            <strong>The Dragon Series</strong> &mdash; a kid finds a dragon egg
            and a four-issue saga unfolds, ending with an unlikely truce.
          </li>
          <li>
            <strong>Dude and the Nudle Bole</strong> &mdash; Alex, Coby, and Cory
            chase the Competadder trophy across three issues of cheerful chaos.
          </li>
          <li>
            <strong>Robotic Wars</strong> &mdash; rebels, bots, lava monsters, and
            a Death Star that just goes BOOM. Three issues, big finale.
          </li>
          <li>
            <strong>Who Knows?</strong> &mdash; a Star-Wars-meets-Venom mashup
            where, true to the title, nobody knows what&apos;s coming next.
          </li>
          <li>
            <strong>The Bones</strong> &mdash; volcanoes, skeletons, and a tank
            ride to return the bones. Three issues.
          </li>
          <li>
            <strong>Dudes in Persute</strong> &mdash; space pursuit comics with
            asteroid belts, motherships, and intentional misspellings.
          </li>
          <li>
            <strong>The Extra Special Comic</strong> &mdash; a two-sided mega-issue
            with car chases on the front and a naval battle on the back.
          </li>
        </ul>
      </section>

      <section className="legal-section">
        <h3>Why everything is free</h3>
        <p>
          Henry didn&apos;t want anyone to miss out because of a paywall, so
          everything on the site is free to read and free to download. A small
          number of ads on comic pages help cover hosting. If you&apos;d like to
          support the shop without ads, the best thing you can do is share a comic
          with a friend who&apos;d enjoy it.
        </p>
      </section>

      <section className="legal-section">
        <h3>Get in touch</h3>
        <p>
          Have a question, fan art, or an idea for a future comic? Use the{' '}
          <a href="/contact">Contact</a> page or email{' '}
          <strong>henryscomicshop@gmail.com</strong>. A grown-up reads everything
          before Henry sees it.
        </p>
      </section>
    </article>
  );
}
